### ISSUE TITLE
Mehere Tasklets?

### ISSUE THREAD

**Issue by manpen** [s9770652/pim-memcpy#1]
Hast du auch mal den Durchsatz für mehrere Tasklets untersucht. In der UpMEM Doku steht

> From the thread standpoint, the apparent latency of any instruction is always one cycle. This is ensured by:
>  - The use of a revolver pipeline at any given time, a thread can have only one instruction in progress in the pipeline, thus pipeline stages don’t have any instruction dependency
> - **A thread which executes a DMA instruction is immediately suspended until the transfer is complete. DMA instructions are the only instruction not entirely executed by the pipeline**

Das könnte bedeuten, dass DMA Instruktionen in Verbindung mit mehr als 11 Taskslets  ggf. Latency-Hiding erlauben.

**Comment by s9770652** [comment]
Ich habe den Abschnitt „On Using Multiple Tasklets“ und einen Absatz bei „Simplified Access“ hinzugefügt.

Wie meine allererste Commit-Nachricht verrät, hatte ich durchaus schon geplant, mir mehrere Tasklets anzuschauen, aber …

- … der Rest hat sich etwas umfangreicher entwickelt als anfangs gedacht und …
- … eine schnelle Implementierung des Multitasking führte zu Kraut und Rüben bei den gemessenen Zahlen, weshalb ich sie wieder entfernte und mich anderen Aspekten widmete. Das tat es auch diesmal, wohinter ich abermals den Compiler vermute. Anstatt dieser Vermutung nachzugehen und mich heute Abend mit Assembler-Code herumzuschlagen, begnüge ich mich damit, dass jetzt mit ein paar Änderungen letztendlich Multitasking mit einem Tasklet doch noch dieselben Ergebnisse wie die ursprüngliche sequentielle Variante liefert.
